# Generated by Django 4.2.4 on 2023-10-17 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_author_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['-id'], 'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
    ]
